site_name: 'Guía de usuario de CiviCRM en español'
site_url: https://docs.civicrm.org/user/es/stable/
repo_url: https://github.com/alejandro-ixiam/civicrm-user-guide-spanish
site_description: 'Guía de usuario de CiviCRM en español.'
site_author: 'La comunidad de CiviCRM'
theme: material
markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite(guess_lang=false)
  - toc(permalink=true)
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

pages:
- Inicio: 'index.md'
- Introducción:
    - '¿Qué es CiviCRM?': 'introduction/what-is-civicrm.md'
    #- 'Real World Examples': 'introduction/real-world-examples.md'
    - 'Componentes': 'introduction/components.md'
    - 'Extensiones': 'introduction/extensions.md'
    - '¿Quién es CiviCRM?': 'introduction/who-is-civicrm.md'
- Poniéndose a punto:
    - '¿Es CiviCRM para usted?': 'getting-prepared/is-civicrm-for-you.md'
    - 'Identificando sus necesidades': 'getting-prepared/identifying-your-needs.md'
    - 'Experimente con CiviCRM': 'getting-prepared/test-it-out.md'
    - 'Alojamiento': 'getting-prepared/hosting.md'
    - 'Implementando CiviCRM': 'getting-prepared/transitioning-to-civicrm.md'
- Configuración Inicial:
    - 'Instalación y configuración básica': 'initial-set-up/installation-and-basic-set-up.md'
    - 'Trabajos programados (inglés)': 'initial-set-up/scheduled-jobs.md'
    - 'Personalizando la interfaz de usuario (inglés)': 'initial-set-up/customizing-the-user-interface.md'
    - 'Permisos y control de acceso (inglés)': 'initial-set-up/permissions-and-access-control.md'
    - 'Seguridad (inglés)': 'initial-set-up/security.md'
    - 'Estado del sistema (inglés)': 'initial-set-up/civicrm-system-status.md'
- Configruación Avanzada:
    - 'Configuración del sistema de email (inglés)': 'advanced-configuration/email-system-configuration.md'
    - 'Registro de cambios y logs (inglés)': 'advanced-configuration/change-logging.md'
- La interfaz de usuario:
    - 'Menú, panel de control y dashlets (inglés)': 'the-user-interface/menu-dashboard-and-dashlets.md'
    - 'Atajos de teclado (inglés)': 'the-user-interface/keyboard-shortcuts.md'
    - 'Búsquedas (inglés)': 'the-user-interface/searching.md'
    - 'No borrar (inglés)': 'the-user-interface/undelete.md'
- Organizando sus datos:
    - 'Resumen (inglés)': 'organising-your-data/overview.md'
    - 'Mapeando sus datos (inglés)': 'organising-your-data/mapping-your-data.md'
    - 'Contactos (inglés)': 'organising-your-data/contacts.md'
    - 'Grupos y etiquetas (inglés)': 'organising-your-data/groups-and-tags.md'
    - 'Smart groups (inglés)': 'organising-your-data/smart-groups.md'
    - 'Actividades (inglés)': 'organising-your-data/activities.md'
    - 'Relaciones (inglés)': 'organising-your-data/relationships.md'
    - 'Creando campos personalizados (inglés)': 'organising-your-data/creating-custom-fields.md'
    - 'Perfiles (inglés)': 'organising-your-data/profiles.md'
- Circuitos habituales:
    - 'Importando datos en CiviCRM (inglés)': 'common-workflows/importing-data-into-civicrm.md'
    - 'Exportar contactos (inglés)': 'common-workflows/exporting-your-contacts.md'
    - 'Deduplicar y fusionar (inglés)': 'common-workflows/deduping-and-merging.md'
    - 'Tokens y combinar correspondencia (inglés)': 'common-workflows/tokens-and-mail-merge.md'
    - 'Comunicaciones postales (inglés)': 'common-workflows/postal-mail-communications.md'
    - 'Automatizando tareas (inglés)': 'common-workflows/automating-tasks.md'
- Contribuciones:
    - '¿Qué es CiviContribute? (inglés)': 'contributions/what-is-civicontribute.md'
    - 'Conceptos clave y configuración (inglés)': 'contributions/key-concepts-and-configurations.md'
    - 'Contribuciones online (inglés)': 'contributions/online-contributions.md'
    - 'Captación de fondos (inglés)': 'contributions/offline-fundraising.md'
    - 'Entrada manual de contribuciones (inglés)': 'contributions/manual-entry-of-contributions.md'
    - 'Buscar y visualizar contribuciones (inglés)': 'contributions/finding-and-viewing-contributions.md'
    - 'Recibos manuales y cartas de agradecimiento (inglés)': 'contributions/manual-receipts-and-thank-yous.md'
    - 'Reportes y análisis (inglés)': 'contributions/reports-and-analysis.md'
    #- 'Soft credits': 'contributions/soft-credits.md'
    #- 'Personal Campaign Pages': 'contributions/personal-campaign-pages.md'
    #- 'Accounting Integration': 'contributions/accounting-integration.md'
    - 'Procesadores de pago (inglés)': 'contributions/payment-processors.md'
    #- 'Invoicing': 'contributions/invoicing.md'
    #- 'Sales tax and VAT': 'contributions/sales-tax-and-vat.md'
    #- 'Premiums': 'contributions/premiums.md'
    #- 'Widgets': 'contributions/widgets.md'
- Compromisos:
    - '¿Qué es CiviPledge? (inglés)': 'pledges/what-is-civipledge.md'
    #- 'What you need to know': 'pledges/what-you-need-to-know.md'
    #- 'Set-up': 'pledges/set-up.md'
    #- 'Everyday tasks': 'pledges/everyday-tasks.md'
    #- 'Pledges Reports and Analysis': 'pledges/pledges-reports-and-analysis.md'
- Eventos:
    - '¿Qué es CiviEvent? (inglés)': 'events/what-is-civievent.md'
    - 'Planificación y gestión de eventos (inglés)': 'events/event-planning-and-management.md'
    - 'Creando un evento (inglés)': 'events/creating-an-event.md'
    - 'Registro online de eventos (inglés)': 'events/online-event-registration.md'
    - 'Integración de eventos con su sitio web (inglés)': 'events/integrating-events-with-your-website.md'
    - 'Registro manual a un evento (inglés)': 'events/manual-event-registration.md'
    - 'Realizar seguimiento de los participantes (inglés)': 'events/keeping-track-of-events-and-participants.md'
    #- 'Complex event fees': 'events/complex-event-fees.md'
    #- 'Event templates': 'events/event-templates.md'
    - 'Reportes (inglés)': 'events/reports.md'
    - 'Datos personalizados para eventos (inglés)': 'events/custom-data-for-events.md'
    - 'Eventos recurrentes (inglés)': 'events/repeating-events.md'
- Socios / Miembros:
    - '¿Qué es CiviMember? (inglés)': 'membership/what-is-civimember.md'
    - 'Definiendo membresías (inglés)': 'membership/defining-memberships.md'
    - 'Alta online de nuevos miembros (inglés)': 'membership/online-membership-sign-up.md'
    - 'Alta manual de nuevos miembreos (inglés)': 'membership/manual-entry-of-memberships.md'
    #- 'Membership price sets': 'membership/membership-price-sets.md'
    - 'Buscar y visualizar membresías (inglés)': 'membership/finding-and-viewing-memberships.md'
    - 'Reportes de membresías (inglés)': 'membership/membership-reports.md'
    #- 'Renewals': 'membership/renewals.md'
    #- 'Cancelling and expiring memberships': 'membership/cancelling-and-expiring-memberships.md'
    #- 'Making member only websites': 'membership/making-member-only-websites.md'
- Correos electrónicos:
    - '¿Qué es CiviMail? (inglés)': 'email/what-is-civimail.md'
    - '¿Qué necesita saber? (inglés)': 'email/what-you-need-to-know.md'
    - 'Configuración (inglés)': 'email/set-up.md'
    - 'Manteniendo listas de distribución saludables (inglés)': 'email/maintaining-healthy-email-lists.md'
    - 'Tareas habituales (inglés)': 'email/everyday-tasks.md'
    - 'Envíos masivos con CiviMail (inglés)': 'email/mass-mailings-using-civimail.md'
    - 'Utilizar tokens en los emails (inglés)': 'email/using-tokens-in-emails.md'
    - 'Reportes y análisis (inglés)': 'email/reports-and-analysis.md'
    - 'Recordatorios programados (inglés)': 'email/scheduled-reminders.md'
    - 'Tests A/B con CiviMail (inglés)': 'email/civimail-ab-testing.md'
- Envío de mensajes de texto (SMS):
    - '¿Qué es CiviSMS?(inglés)': 'sms-text-messaging/what-is-sms.md'
    - 'Configuración (inglés)': 'sms-text-messaging/set-up.md'
    - 'Tareas habituales (inglés)': 'sms-text-messaging/everyday-tasks.md'
    - 'Reportes y análisis (inglés)': 'sms-text-messaging/reports-and-analysis-sms.md'
- Reportes:
    - '¿Qué es CiviReport? (inglés)': 'reporting/what-is-civireport.md'
    - '¿Qué necesita saber? (inglés)': 'reporting/what-you-need-to-know.md'
    - 'Configuración (inglés)': 'reporting/set-up.md'
    - 'Tareas habituales (inglés)': 'reporting/everyday-tasks.md'
- Gestión de casos:
    - '¿Qué es CiviCase? (inglés)': 'case-management/what-is-civicase.md'
    - '¿Qué necesita saber (inglés)': 'case-management/what-you-need-to-know.md'
    - 'Configuración (inglés)': 'case-management/set-up.md'
    - 'Tareas habituales (inglés)': 'case-management/everyday-tasks.md'
    - 'Reportes y análisis (inglés)': 'case-management/reports-and-analysis.md'
- Campañas:
    - '¿Qué es CiviCampaign? (inglés)': 'campaign/what-is-civicampaign.md'
    - '¿Qué necesita saber? (inglés)': 'campaign/what-you-need-to-know.md'
    - 'Configuración (inglés)': 'campaign/set-up.md'
    - 'Tareas habituales (inglés)': 'campaign/everyday-tasks.md'
    - 'Reportes y análisis (inglés)': 'campaign/reports-and-analysis.md'
- Encuestas:
    - '¿Qué es CiviSurvey? (inglés)': 'survey/what-is-civisurvey.md'
    - '¿Qué necesita saber? (inglés)': 'survey/what-you-need-to-know.md'
    - 'Configuración (inglés)': 'survey/set-up.md'
    - 'Tareas habituales (inglés)': 'survey/everyday-tasks.md'
    - 'Reportes y análisis (inglés)': 'survey/reports-and-analysis.md'
    - 'Qué es GOTV (Control de votos)?': 'survey/what-is-gotv-voter-tracking.md'
- Peticiones:
    - '¿Qué es CiviPetition? (inglés)': 'petition/what-is-civipetition.md'
    - '¿Qué necesita saber? (inglés)': 'petition/what-you-need-to-know.md'
    - 'Configuración (inglés)': 'petition/set-up.md'
    - 'Tareas habituales (inglés)': 'petition/everyday-tasks.md'
    - 'Reportes y análisis (inglés)': 'petition/reports-and-analysis.md'
- Integración con sitios web:
    - 'Eligiendo un CMS (inglés)': 'website-integration/choosing-your-cms.md'
    - 'Integración con Drupal (inglés)': 'website-integration/integrating-with-drupal.md'
    - 'Integración con WordPress (inglés)': 'website-integration/integrating-with-wordpress.md'
    - 'Integración con Joomla (inglés)': 'website-integration/integrating-with-joomla.md'
#- The CiviCRM Community:
    #- 'The CiviCRM Community': 'the-civicrm-community/the-civicrm-community.md'
    #- 'Bug Reporting': 'the-civicrm-community/bug-reporting.md'
    #- 'Localising CiviCRM': 'the-civicrm-community/localising-civicrm.md'
    #- 'Contributing to this manual': 'the-civicrm-community/contributing-to-this-manual.md'
#- Civic Engagement:
    #- 'What is CiviEngage?': 'civic-engagement/what-is-civiengage.md'
    #- 'What You Need To Know': 'civic-engagement/what-you-need-to-know.md'
    #- 'Set-up': 'civic-engagement/set-up.md'
    #- 'Everyday Tasks': 'civic-engagement/everyday-tasks.md'
    #- 'Reports and analysis': 'civic-engagement/reports-and-analysis.md'
#- Grants:
    #- 'What is CiviGrant?': 'grants/what-is-civigrant.md'
    #- 'What You Need To Know': 'grants/what-you-need-to-know.md'
    #- 'Set-up': 'grants/set-up.md'
    #- 'Everyday tasks': 'grants/every-day-tasks.md'
    #- 'Reports and analyis': 'grants/reports-and-analysis.md'
#- Appendices:
    #- 'History of this book': 'appendices/history-of-this-book.md'
    #- 'Free Software?': 'appendices/free-software.md'
    #- 'Glossary': 'appendices/glossary.md'
    #- 'Credits': 'appendices/credits.md'
